export const ENV_KEYS = {
  PROTOCOL: 'PROTOCOL',
  HOST: 'HOST',
  JWT_SECRET: 'JWT_SECRET',
  HASH_ROUNDS: 'HASH_ROUNDS',
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_DATABASE: 'DB_DATABASE',
};
